name: downloader_video_prod
services:
  redis:
    restart: unless-stopped
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

  postgres:
    restart: unless-stopped
    image: postgres:16
    env_file:
      - .env.postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  downloader_video:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: downloader_video:latest
    ports:
      - "8084:80"
    volumes:
      - ./.env:/.env:ro
      - ./app:/app:ro
      - downloads:/downloads
    environment:
      - DOWNLOAD_FOLDER=/downloads
    depends_on:
      - redis
      - postgres

  worker:
    restart: unless-stopped
    image: downloader_video:latest
    depends_on:
      - redis
      - postgres
    volumes:
      - ./.env:/.env:ro
      - ./app:/app:ro
      - downloads:/downloads
    environment:
      - DOWNLOAD_FOLDER=/downloads
    command: ["python", "-m", "arq", "app.worker.WorkerSettings"]

volumes:
  downloads:
