services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

  downloader_video:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: downloader_video:latest
    ports:
      - "8084:80"
    volumes:
      - ./.env:/.env:ro
    depends_on:
      - redis

volumes:
  redis_data: