services:
  downloader_video:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: downloader_video:latest
    ports:
      - "8084:80"
    volumes:
      - ./.env:/.env:ro