name: downloader_test
services:
  redis:
    container_name: downloader_redis_test
    restart: unless-stopped
    image: redis:7-alpine
    ports:
      - "63799:6379"
    volumes:
      - ./redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

  postgres:
    restart: unless-stopped
    image: postgres:16
    env_file:
      - .env.postgres
    ports:
      - "54322:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  downloader_video:
    container_name: downloader_video_test
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: downloader_video_test:latest
    ports:
      - "8085:80"
    volumes:
      - ./.env:/.env:ro
      - ./app:/app:ro
    depends_on:
      - redis
      - postgres
